---
- hosts: webservers
  sudo: yes
  vars:
  - http_port: 8080
  roles:
  - nginx


- hosts: loadbalancers
  sudo: yes
  vars:
  - http_port: 8080
  - load_balancer_port: 80
  tasks:
  - name: install nginx
    yum: name=nginx

  - name: configure nginx as a load balancer
    template: src=load-balancer.j2 dest=/etc/nginx/conf.d/default.conf

  - name: start nginx and ensure it is enabled at boot time
    service: name=nginx enabled=yes state=restarted
