---
- name: download the EPEL repository definitions
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel.rpm

- name: enable the EPEL repository definitions
  command: rpm -i --force /tmp/epel.rpm

- name: ensure nginx is installed
  yum: name=nginx state=installed

- name: modify the default config to use the given http port
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: 
  - restart nginx

- name: customize the default static website
  copy: src={{ item}} dest=/usr/share/nginx/html
  with_items:
  - index.html
  - image.jpg
  notify:
  - restart nginx 

- name: ensure that nginx runs at boot time.
  service: name=nginx enabled=yes
